version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    env_file:
      - ./frontend/.env/dev.injected.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: gatsblog_frontend_dev
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app/src

